### ISSUE TITLE
Not using latest version of mysql-connector-java in examples

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/cloud-sql-mysql-socket-factory#28]
https://github.com/GoogleCloudPlatform/cloud-sql-mysql-socket-factory/blob/master/examples/compute-engine/pom.xml#L46

The latest version is 6.0.5
https://mvnrepository.com/artifact/mysql/mysql-connector-java

The example shows 5.1.39

**Comment by laixer** [comment]
6.0.5 is a development release. It's unfortunate that their version numbers are so confusing.

**Comment by tswast** [comment]
Yeah, that is confusing. Is 5.1.40 a stable package?

**Comment by laixer** [comment]
yes 5.1.40 is the latest release version
