### ISSUE TITLE
Dependency should use version boundries

### ISSUE THREAD

**Issue by saturnism** [GoogleCloudPlatform/cloud-sql-mysql-socket-factory#30]
Do we require use of a specific version of the MySQL Connector/J version? Or just the major release version? If not a specific version, consider using a boundary.

**Comment by laixer** [comment]
Version ranges are best avoided as they produce non-deterministic/non-reproducible builds.
If you would like to use version ranges, I would recommend doing so in your application's dependency specifications.

**Comment by laixer** [comment]
Sorry, I missed part of your question. You can use any Connector/J release with the same major version. 
My reasoning for not adding a version range is above.
